export const ApiRoutes = {
  products: 'products',
  product: 'product',
  brandWithProducts: 'brand/product/slider',
  brand: 'brand',
  category: 'category',
  quickCategories: 'quick-categories',
  tag: 'tag',
  setting: 'setting',
  banners: 'banners',
  signin: 'auth/sign-in',
  signup: 'auth/sign-up',
  address: 'address',
  createAddress: 'address/create',
  updateAddress: 'address/update',
  deleteAddress: 'address/delete',
  paymentMethods: 'enum/payment-method',
  shippingMethods: 'enum/shipping-method',
  checkoutIdentifiedOrder: 'order/checkout/identified',
} as const;
